---
title: "R Practice"
author: "Eric Miedema"
output:
  md_document:
    variant: markdown_github
---

# Data Analytics with R

This is content of [swirl](http://swirlstats.com) instructions and practice problems for data analytics with R.

## Class Set Up

This course is forked from the [swirl GitHub repository](https://github.com/swirldev/swirl) and leverages the [swirl R package](http://swirlstats.com). 

For more information regarding swirl, visit [swirlstats.com](http://swirlstats.com) or the [swirl GitHub repository](https://github.com/swirldev/swirl).

### Install and run a course automatically from swirl

**This is the preferred method of installing courses.** It automates the process by allowing you to do everything right from the R console.

1) Make sure you have a recent version version of swirl:

``` {r}
install.packages("swirl")
```

2) Enter the following from the R console:

```
library(swirl)
install_course_github('ericmiedema','Data_Analytics')
swirl()
```

3)  If error with automatic download.  Download zip GitHub directly and load from zip.

```
library(swirl)
install_course_zip("path/to/file/here/Data_Analytics-master.zip", multi=TRUE, 
                   which_course="Data Analytics")
swirl()
```

### Uninstall a course

If you'd like to remove a course at any time, you can use `uninstall_course("Course Name Here")`.

## 1: Introduction to data analytics with R

## Introduction to R

[Download R](https://cran.r-project.org/) and [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/).  

* install.packages("package") - Install a single or list of packages
* setwd("/folder path") - Set working directory to specific folder
* read.csv("file.csv", headers = TRUE, stringsAS Factor = FALSE) - Read csv file

HOT KEYS  

1. Ctrl + L (clear workspace)
2. Ctrl + A (select all code)
3. Ctrl + Enter (run selected code)

## Excel R Function Comparison

Excel  | R | Use
------------- | ------------- | -------------
sum() | sum() | sum of data
sqrt()  | sqrt() | sqrt of data
average() | mean() | mean of data
norm.dist() | pnorm() | area under z distribution
norm.inv() | qnorm() | lookup Z score with probability
t.dist() | pt() | area under t distribution
t.inv() | qt() | lookup t score with probability
$f_x$ button | help() | help on function
Cope paste transpose | t() | transpose data
vlookup() | NA | Cell lookup are not applicable in R

## Apply

### Problem 1

A [venous thromboembolism (VTE)](https://en.wikipedia.org/wiki/Venous_thrombosis), is a blood clot that breaks loose and travels in the blood.  This may cause serious life-threatening condition such as a heart attack or stroke.  A d-dimer test is a blood test that measures a substance that is released when there is a blood clot and can be used to assess the likelihood of a VTE. 

1. What is the probability of a VTE with a positive d-dimer?
2. What is the probability of a VTE with a negative d-dimer?

```
# Random Patient Generator
vte_patients<-500 + rnorm(1, mean = 50, sd = 10)
non_vte_patient<-vte_patients*10 + rnorm(1, mean = 100, sd = 20)
genders<-c("M","F")

df_vte<-data.frame(
  Gender = sample(genders,vte_patients,replace = TRUE),
  Age = round(runif(vte_patients,0,15)+rnorm(vte_patients, mean = 50, sd = 10),0),
  D_Dimer = rbinom(vte_patients, 1, .8),
  VTE = 1)

## probability of VTE with a positive d-dimer

## probability of VTE with a positive d-dimer
```

### Problem 2

Imagine that Tennessee is having an election on the location of its capital.  Using [ranked pairs](https://en.wikipedia.org/wiki/Ranked_pairs) method determine where the capital should be.

```
options(stringsAsFactors = FALSE)
population<-data.frame(City = c("Memphis","Nashville","Chattanooga","Knoxville"), Percent = c(.42,.26,.15,.17))
Memphis<-data.frame(City = c("Memphis","Nashville","Chattanooga","Knoxville"),Rank = 1:4)
Nashville<-data.frame(City = c("Nashville","Chattanooga","Knoxville","Memphis"),Rank = 1:4)
Chattanooga<-data.frame(City = c("Chattanooga","Knoxville","Nashville","Memphis"),Rank = 1:4)
Knoxville<-data.frame(City = c("Knoxville","Chattanooga","Nashville","Memphis"),Rank = 1:4)

# Compare Memphis and Nashville
# Compare other all cities
# Determine winner
```

### Base Functions

*  Generating, loading and combining data
    + Read/Write
    + Combining c(), rbind()/cbind(), merge(), unique()
*  Subsetting
    +  a<-Data[Data$Character_variable %in% c('ABC','XYZ'),]
    +  b<-Data[Data$Numeric_variable == 1,c(1,"Column B",3)] 
    +  Special characters: $,==,!, &, |, ~
    +  Data Types: Data Frames, Factors, Strings, Date/Time, NA  
* Programming
    + User defined functions
    + For/while and if/elseif/then 
    + Lapply and Mapply
* R workspace / Package Maintanance
    + getwd(),setwd()
    + install.packages('dply',dependencies = TRUE), library(dplyr)
    + rm(), ls(), rm(ls())

[Intro to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)  
[Base R - Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf)

### Data Wrangling

* Reshaping Data
* Group & Summarize
* Alternative approach to combine and subset data

[Data Wrangling - Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

## Practice Examples

### Descriptive Statistics Practice

Base on a random generated data for adult patients, what is the standard deviation 

```
set.seed(200)
ages<-round(rnorm(200,mean = 55, sd = 15),0) #list
df<-data.frame(Age = ages) #data frame
# Calculate the mean - using sum/length, mean or summary functions

# Calculate the standard deviations

# Calcualte the z score and percentage for 65 year olds
```

Practice #2 - Benchmarking

```
install.packages("RSocrata")
library(RSocrata)
comp<-read.socrata("https://data.medicare.gov/resource/ukfj-tt6v.csv")

# What is the top decile for the rate of complications for hip/knee replacement patients?
```


### Probability

Practice #1 - Probability of Events

Yahtzee!  Use the **law of large numbers** and the power of R to generate large amounts of random data to indicate the probability of Yahtzee on the first roll.  Bonus problem is if it is your last turn and you have 3 rolls to get Yatzee.

```
# What is the probability of getting Yatzee?
library(tidyr)
library(dplyr)

set.seed(31)

rolls<-50000 #Number of rolls
df<-data.frame(D1 = sample(1:6,rolls,replace = TRUE), D2 = sample(1:6,rolls,replace = TRUE),D3= sample(1:6,rolls,replace = TRUE),
               D4 = sample(1:6,rolls,replace = TRUE), D5 = sample(1:6,rolls,replace = TRUE))
df$Roll<-1:rolls 
```

Practice #2 - Probability of Distributions

### Working with Dates

A common frustration with R is working with dates especially when combining data from multiple sources.  There are packages such as 'lubridate` that can support, but knowing how to work with dates and write user defined functions to fix problems will help overcome the frustration.

Practice #1: Transform this list of dates to a standard format.

```
dates_are_the_worst<-c("2-01-2018","03-03-2018","1/1/2018","2018-04-02 00:00:00")
df<-data.frame(Date = dates_are_the_worst) #data frame
# Transform to date format
```

Practice #2: Take lessons learned from practice #1 to write a user defined function to another list of dates.

```
dates_are_the_worst<-c("2-01-2018","5/1/2018 1:23 PM","03-03-2018","1/1/2018","2018-04-02 00:00:00")
another_date_list<-c("3/2/2018 23:22","6/1/2018 1:23 PM","5-4-2018","1/1/2018","2018-03-01 00:00:00")
# Transform to date lists format with user defined function
```

### Working with Strings

Large amounts of data is freetext instead of discrete elements defined by a list or form.  Also the source of data could be a PDF or website as large text.  In order to analyze strings, the categorical or numeric data needs to be extracted from the larger text.

Practice #1:  Extracting data from  string

```
messy_string<-c("Here is some text that we want to format: Name = Eric Miedema, Birthday = 12/12/1987, Age = 30, Name = Noah Boggess,  Birthday = NA, Age = 35. END of document")

# Create a data frame with Name, Birthday, Age columns
```

Additional, R file, string or base functions can help organize data or text from multiple files.

Practice #2:  Collapse data multiple files into a single string

```
set.seed(15)
dir.create("Fake_Data") #create folder
# Add random data
for(i in seq_along(letters)){
  write.csv(data.frame(Data = floor(rnorm(15, mean = 100, sd =5))),
            paste("Fake_Data/",letters[i],'.csv',sep = ""),row.names = FALSE)
}

# Collapse data multiple files into a single string
```